# Generated by Django 2.1.1 on 2018-09-10 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('image', models.FileField(blank=True, upload_to='profile_images/')),
                ('isBand', models.BooleanField(default='False')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('mp3', models.FileField(upload_to='mp3/')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BandProfile')),
                ('genre', models.ManyToManyField(to='api.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('image', models.FileField(blank=True, upload_to='profile_images/')),
                ('liked', models.ManyToManyField(to='api.Song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
