# Generated by Django 2.1.1 on 2018-09-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
